package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type student struct {
	Name  string
	Class int
	Age   int
}
type Autogenerated struct {
	Name  string `json:"Name"`
	Class int    `json:"Class"`
	Age   int    `json:"Age"`
}

func main() {
	fmt.Println("json")
	s := student{"sum", 10, 11}
	s1 := student{"div", 2, 6}
	S := []student{s, s1}
	//Marshhalling data (struct to json)
	out, err := json.Marshal(S)
	if err != nil {
		fmt.Println("err: ", err)
	}
	fmt.Println(string(out))
	//Unmarshalling data (json to struct)
	u := `[{"Name":"sum","Class":10,"Age":12},{"Name":"div","Class":2,"Age":6}]`
	var unmar []Autogenerated
	_ = json.Unmarshal([]byte(u), &unmar)
	fmt.Println(unmar)
	err = json.NewEncoder(os.Stdout).Encode(S)
	if err != nil {
		fmt.Println("err", err)
	}
	fmt.Println("NewEncoder:\n", S)
}
